my-commit

diff --git a/.github/workflows/deployment.yml b/.github/workflows/deployment.yml
--- a/.github/workflows/deployment.yml
+++ b/.github/workflows/deployment.yml
@@ -33,7 +33,7 @@ jobs:
           username: abubakar
           key: ${{ secrets.HOSTINGER_SSH_KEY }}
           script: |
-            # Check if the tarball already exists and remove it if needed
+            # Clean up any existing tarball and Docker image
             if [ -f /home/abubakar/my-app.tar.gz ]; then
               echo "Found existing tarball, removing it..."
               rm /home/abubakar/my-app.tar.gz
@@ -42,13 +42,14 @@ jobs:
               echo "Found existing tar file, removing it..."
               rm /home/abubakar/my-app.tar
             fi
+            if docker ps -a --format '{{.Names}}' | grep -q 'my-app'; then
+              echo "Stopping and removing existing container..."
+              docker rm -f my-app || true
+            fi
 
             # Decompress and load the Docker image
             gunzip /home/abubakar/my-app.tar.gz
             docker load < /home/abubakar/my-app.tar
-
-            # Stop and remove any running container with the same name
-            docker rm -f my-app || true
 
             # Run the Docker container
             docker run -d -p 4173:4173 --name my-app my-app
